export type countryTypes = {
  [key: string]: { color: string; name: string };
};

export const countries: countryTypes = {
  AF: { color: '#4454d6', name: 'Afghanistan' },
  AX: { color: '#595ccc', name: 'åland Islands' },
  AL: { color: '#b34cdd', name: 'Albania' },
  DZ: { color: '#71675a', name: 'Algeria' },
  AS: { color: '#8dc7de', name: 'American Samoa' },
  AD: { color: '#8a62da', name: 'Andorra' },
  AO: { color: '#878163', name: 'Angola' },
  AI: { color: '#bac4a9', name: 'Anguilla' },
  AQ: { color: '#690e01', name: 'Antarctica' },
  AG: { color: '#7e447d', name: 'Antigua And Barbuda' },
  AR: { color: '#4711e5', name: 'Argentina' },
  AM: { color: '#712fe4', name: 'Armenia' },
  AW: { color: '#3281ab', name: 'Aruba' },
  AU: { color: '#b45938', name: 'Australia' },
  AT: { color: '#53ca50', name: 'Austria' },
  AZ: { color: '#fd32e3', name: 'Azerbaijan' },
  BS: { color: '#52b02e', name: 'Bahamas' },
  BH: { color: '#7e2e0c', name: 'Bahrain' },
  BD: { color: '#99b3d3', name: 'Bangladesh' },
  BB: { color: '#470b5a', name: 'Barbados' },
  BY: { color: '#c5b60a', name: 'Belarus' },
  BE: { color: '#060287', name: 'Belgium' },
  BZ: { color: '#fea4bf', name: 'Belize' },
  BJ: { color: '#4941d4', name: 'Benin' },
  BM: { color: '#9fe905', name: 'Bermuda' },
  BT: { color: '#9b2bcc', name: 'Bhutan' },
  BO: { color: '#2ffb04', name: 'Bolivia, Plurinational State Of' },
  BQ: { color: '#4af963', name: 'Bonaire, Sint Eustatius And Saba' },
  BA: { color: '#a70928', name: 'Bosnia And Herzegovina' },
  BW: { color: '#0cccc1', name: 'Botswana' },
  BV: { color: '#4cb143', name: 'Bouvet Island' },
  BR: { color: '#c5f4d7', name: 'Brazil' },
  IO: { color: '#3000ce', name: 'British Indian Ocean Territory' },
  BN: { color: '#dbaa46', name: 'Brunei Darussalam' },
  BG: { color: '#f5b336', name: 'Bulgaria' },
  BF: { color: '#32defa', name: 'Burkina Faso' },
  BI: { color: '#c6529c', name: 'Burundi' },
  KH: { color: '#948ef7', name: 'Cambodia' },
  CM: { color: '#262e90', name: 'Cameroon' },
  CA: { color: '#5bc222', name: 'Canada' },
  CV: { color: '#f6d7ad', name: 'Cape Verde' },
  KY: { color: '#5b8268', name: 'Cayman Islands' },
  CF: { color: '#421cf5', name: 'Central African Republic' },
  TD: { color: '#304eb4', name: 'Chad' },
  CL: { color: '#eedb36', name: 'Chile' },
  CN: { color: '#5c7687', name: 'China' },
  CX: { color: '#88743e', name: 'Christmas Island' },
  CC: { color: '#57137b', name: 'Cocos (Keeling) Islands' },
  CO: { color: '#928027', name: 'Colombia' },
  KM: { color: '#93883f', name: 'Comoros' },
  CG: { color: '#6eec80', name: 'Congo' },
  CD: { color: '#a795e4', name: 'Congo, The Democratic Republic Of The' },
  CK: { color: '#28ee78', name: 'Cook Islands' },
  CR: { color: '#bdd1af', name: 'Costa Rica' },
  CI: { color: '#8d72f8', name: "Côte D'ivoire" },
  HR: { color: '#7cc55d', name: 'Croatia' },
  CU: { color: '#2ac2d8', name: 'Cuba' },
  CW: { color: '#21db41', name: 'Curaçao' },
  CY: { color: '#d87e89', name: 'Cyprus' },
  CZ: { color: '#57327f', name: 'Czech Republic' },
  DK: { color: '#644ea5', name: 'Denmark' },
  DJ: { color: '#9fe1d0', name: 'Djibouti' },
  DM: { color: '#3fb484', name: 'Dominica' },
  DO: { color: '#206e47', name: 'Dominican Republic' },
  EC: { color: '#dd4907', name: 'Ecuador' },
  EG: { color: '#ee866c', name: 'Egypt' },
  SV: { color: '#1efa06', name: 'El Salvador' },
  GQ: { color: '#c2fc84', name: 'Equatorial Guinea' },
  ER: { color: '#73ba89', name: 'Eritrea' },
  EE: { color: '#8b0e5a', name: 'Estonia' },
  ET: { color: '#d5731d', name: 'Ethiopia' },
  FK: { color: '#f0514f', name: 'Falkland Islands (Malvinas)' },
  FO: { color: '#882be4', name: 'Faroe Islands' },
  FJ: { color: '#b8523b', name: 'Fiji' },
  FI: { color: '#498ebc', name: 'Finland' },
  FR: { color: '#79e846', name: 'France' },
  GF: { color: '#2c8caa', name: 'French Guiana' },
  PF: { color: '#7a9e61', name: 'French Polynesia' },
  TF: { color: '#4696c4', name: 'French Southern Territories' },
  GA: { color: '#935267', name: 'Gabon' },
  GM: { color: '#a9e3d2', name: 'Gambia' },
  GE: { color: '#2c87e1', name: 'Georgia' },
  DE: { color: '#61e515', name: 'Germany' },
  GH: { color: '#d892f8', name: 'Ghana' },
  GI: { color: '#9f60c4', name: 'Gibraltar' },
  GR: { color: '#855521', name: 'Greece' },
  GL: { color: '#fad544', name: 'Greenland' },
  GD: { color: '#fc1f6f', name: 'Grenada' },
  GP: { color: '#0aa05b', name: 'Guadeloupe' },
  GU: { color: '#61e418', name: 'Guam' },
  GT: { color: '#78ab33', name: 'Guatemala' },
  GG: { color: '#fb1a49', name: 'Guernsey' },
  GN: { color: '#6d1426', name: 'Guinea' },
  GW: { color: '#ae9f68', name: 'Guinea Bissau' },
  GY: { color: '#e14151', name: 'Guyana' },
  HT: { color: '#80d059', name: 'Haiti' },
  HM: { color: '#db72d8', name: 'Heard Island And Mcdonald Islands' },
  VA: { color: '#bdbcbe', name: 'Holy See (Vatican City State)' },
  HN: { color: '#baa61b', name: 'Honduras' },
  HK: { color: '#24dea4', name: 'Hong Kong' },
  HU: { color: '#118464', name: 'Hungary' },
  IS: { color: '#e92865', name: 'Iceland' },
  IN: { color: '#f6b638', name: 'India' },
  ID: { color: '#5c2fad', name: 'Indonesia' },
  IR: { color: '#b2a76b', name: 'Iran, Islamic Republic Of' },
  IQ: { color: '#3bb6c9', name: 'Iraq' },
  IE: { color: '#13eec8', name: 'Ireland' },
  IM: { color: '#ba2811', name: 'Isle Of Man' },
  IL: { color: '#063abe', name: 'Israel' },
  IT: { color: '#886907', name: 'Italy' },
  JM: { color: '#5ce6b2', name: 'Jamaica' },
  JP: { color: '#940a70', name: 'Japan' },
  JE: { color: '#e42820', name: 'Jersey' },
  JO: { color: '#078695', name: 'Jordan' },
  KZ: { color: '#0b510a', name: 'Kazakhstan' },
  KE: { color: '#29a24a', name: 'Kenya' },
  KI: { color: '#3a24ac', name: 'Kiribati' },
  KP: { color: '#e36a12', name: "Korea, Democratic People's Republic Of" },
  KR: { color: '#db89db', name: 'Korea, Republic Of' },
  KW: { color: '#6e8751', name: 'Kuwait' },
  KG: { color: '#914f28', name: 'Kyrgyzstan' },
  LA: { color: '#0b11ea', name: "Lao People's Democratic Republic" },
  LV: { color: '#f78c30', name: 'Latvia' },
  LB: { color: '#7dd37d', name: 'Lebanon' },
  LS: { color: '#d906a8', name: 'Lesotho' },
  LR: { color: '#38ff0f', name: 'Liberia' },
  LY: { color: '#b2b46c', name: 'Libya' },
  LI: { color: '#38b10e', name: 'Liechtenstein' },
  LT: { color: '#bb6280', name: 'Lithuania' },
  LU: { color: '#615738', name: 'Luxembourg' },
  MO: { color: '#7ba5d8', name: 'Macao' },
  MK: { color: '#3b4429', name: 'Macedonia, The Former Yugoslav Republic Of' },
  MG: { color: '#fb7a27', name: 'Madagascar' },
  MW: { color: '#69062d', name: 'Malawi' },
  MY: { color: '#6d1d4a', name: 'Malaysia' },
  MV: { color: '#2646d6', name: 'Maldives' },
  ML: { color: '#21bc02', name: 'Mali' },
  MT: { color: '#e0615d', name: 'Malta' },
  MH: { color: '#67d607', name: 'Marshall Islands' },
  MQ: { color: '#62ee33', name: 'Martinique' },
  MR: { color: '#673702', name: 'Mauritania' },
  MU: { color: '#7a0708', name: 'Mauritius' },
  YT: { color: '#a55aa0', name: 'Mayotte' },
  MX: { color: '#e1d927', name: 'Mexico' },
  FM: { color: '#094728', name: 'Micronesia, Federated States Of' },
  MD: { color: '#4eb6fe', name: 'Moldova, Republic Of' },
  MC: { color: '#c57b9e', name: 'Monaco' },
  MN: { color: '#5a432d', name: 'Mongolia' },
  ME: { color: '#b166f9', name: 'Montenegro' },
  MS: { color: '#889065', name: 'Montserrat' },
  MA: { color: '#c124da', name: 'Morocco' },
  MZ: { color: '#8debdf', name: 'Mozambique' },
  MM: { color: '#2e4216', name: 'Myanmar' },
  NA: { color: '#22dce9', name: 'Namibia' },
  NR: { color: '#6873f2', name: 'Nauru' },
  NP: { color: '#1fb1b5', name: 'Nepal' },
  NL: { color: '#b0eb4d', name: 'Netherlands' },
  NC: { color: '#39cbbc', name: 'New Caledonia' },
  NZ: { color: '#aa9b1b', name: 'New Zealand' },
  NI: { color: '#3e0f2c', name: 'Nicaragua' },
  NE: { color: '#9ef4e1', name: 'Niger' },
  NG: { color: '#d1a6a5', name: 'Nigeria' },
  NU: { color: '#2df60e', name: 'Niue' },
  NF: { color: '#1cb8c9', name: 'Norfolk Island' },
  MP: { color: '#8ccf09', name: 'Northern Mariana Islands' },
  NO: { color: '#b57163', name: 'Norway' },
  OM: { color: '#bb738b', name: 'Oman' },
  PK: { color: '#205c48', name: 'Pakistan' },
  PW: { color: '#c15094', name: 'Palau' },
  PS: { color: '#65f479', name: 'Palestine, State Of' },
  PA: { color: '#273a98', name: 'Panama' },
  PG: { color: '#079f26', name: 'Papua New Guinea' },
  PY: { color: '#957bb2', name: 'Paraguay' },
  PE: { color: '#ac7b56', name: 'Peru' },
  PH: { color: '#74a784', name: 'Philippines' },
  PN: { color: '#988176', name: 'Pitcairn' },
  PL: { color: '#3ceee7', name: 'Poland' },
  PT: { color: '#c5ae05', name: 'Portugal' },
  PR: { color: '#edf957', name: 'Puerto Rico' },
  QA: { color: '#92ce76', name: 'Qatar' },
  RE: { color: '#f239c2', name: 'Réunion' },
  RO: { color: '#223643', name: 'Romania' },
  RU: { color: '#c4efe5', name: 'Russian Federation' },
  RW: { color: '#72b186', name: 'Rwanda' },
  BL: { color: '#997222', name: 'Saint Barthélemy' },
  SH: {
    color: '#fb23ca',
    name: 'Saint Helena, Ascension And Tristan Da Cunha',
  },
  KN: { color: '#b8e144', name: 'Saint Kitts And Nevis' },
  LC: { color: '#d6cbfb', name: 'Saint Lucia' },
  MF: { color: '#a4865d', name: 'Saint Martin (French Part)' },
  PM: { color: '#221faf', name: 'Saint Pierre And Miquelon' },
  VC: { color: '#10e3eb', name: 'Saint Vincent And The Grenadines' },
  WS: { color: '#02fc27', name: 'Samoa' },
  SM: { color: '#0c08bc', name: 'San Marino' },
  ST: { color: '#ce34e6', name: 'Sao Tome And Principe' },
  SA: { color: '#4a8dbe', name: 'Saudi Arabia' },
  SN: { color: '#987b4e', name: 'Senegal' },
  RS: { color: '#5716ac', name: 'Serbia' },
  SC: { color: '#3fe81d', name: 'Seychelles' },
  SL: { color: '#e7fe21', name: 'Sierra Leone' },
  SG: { color: '#e1ee3d', name: 'Singapore' },
  SX: { color: '#d2461d', name: 'Sint Maarten (Dutch Part)' },
  SK: { color: '#95cafe', name: 'Slovakia' },
  SI: { color: '#7beb33', name: 'Slovenia' },
  SB: { color: '#aee552', name: 'Solomon Islands' },
  SO: { color: '#33bbbb', name: 'Somalia' },
  ZA: { color: '#f7e101', name: 'South Africa' },
  GS: {
    color: '#24be38',
    name: 'South Georgia And The South Sandwich Islands',
  },
  SS: { color: '#c825c9', name: 'South Sudan' },
  ES: { color: '#abf0dd', name: 'Spain' },
  LK: { color: '#f9a6b4', name: 'Sri Lanka' },
  SD: { color: '#f4ffbd', name: 'Sudan' },
  SR: { color: '#fbb20e', name: 'Suriname' },
  SJ: { color: '#2f6bed', name: 'Svalbard And Jan Mayen' },
  SZ: { color: '#6054f9', name: 'Swaziland' },
  SE: { color: '#d7777b', name: 'Sweden' },
  CH: { color: '#975cc1', name: 'Switzerland' },
  SY: { color: '#424a18', name: 'Syrian Arab Republic' },
  TW: { color: '#248988', name: 'Taiwan, Province Of China' },
  TJ: { color: '#95dcc8', name: 'Tajikistan' },
  TZ: { color: '#5d6b73', name: 'Tanzania, United Republic Of' },
  TH: { color: '#c7704c', name: 'Thailand' },
  TL: { color: '#862299', name: 'Timor Leste' },
  TG: { color: '#c82b27', name: 'Togo' },
  TK: { color: '#42c519', name: 'Tokelau' },
  TO: { color: '#03e519', name: 'Tonga' },
  TT: { color: '#3e787f', name: 'Trinidad And Tobago' },
  TN: { color: '#4514c8', name: 'Tunisia' },
  TR: { color: '#291bc8', name: 'Turkey' },
  TM: { color: '#093941', name: 'Turkmenistan' },
  TC: { color: '#9f69d5', name: 'Turks And Caicos Islands' },
  TV: { color: '#b40dd5', name: 'Tuvalu' },
  UG: { color: '#6a7aae', name: 'Uganda' },
  UA: { color: '#0f62b7', name: 'Ukraine' },
  AE: { color: '#605e99', name: 'United Arab Emirates' },
  GB: { color: '#6be1fc', name: 'United Kingdom' },
  US: { color: '#278943', name: 'United States' },
  UM: { color: '#950d1a', name: 'United States Minor Outlying Islands' },
  UY: { color: '#58e4e5', name: 'Uruguay' },
  UZ: { color: '#4fd5f6', name: 'Uzbekistan' },
  VU: { color: '#b2459b', name: 'Vanuatu' },
  VE: { color: '#0e5172', name: 'Venezuela, Bolivarian Republic Of' },
  VN: { color: '#3f57f0', name: 'Vietnam' },
  VG: { color: '#22c0d1', name: 'Virgin Islands, British' },
  VI: { color: '#e16910', name: 'Virgin Islands, U.S.' },
  WF: { color: '#4a508c', name: 'Wallis And Futuna' },
  EH: { color: '#923191', name: 'Western Sahara' },
  YE: { color: '#7d7255', name: 'Yemen' },
  ZM: { color: '#00c88d', name: 'Zambia' },
  ZW: { color: '#954801', name: 'Zimbabwe' },
};
